qualityGate:
  coverage:
    acceptedDeltaPercentage: 5
    enabled: true
  codeAnalysis:
    highsLimit: 0
    mediumsLimit: 0
    lowsLimit: 0
    spamThreshold: 10
    enabled: true
  JIRA:
    enabled: false
reviewersRaffle:
  strategies:
    - my-candidates:
        type: sequential
        size: 1
        participants:
          users:
            - dany
            - miguel
            - yichun
            - jorge-poblete
            - ana-mora
            - luis-teran
            - mauro
            - piero-valdebenito
            - diego-hernandez
  dailyReminder: enabled
slack:
  - "#yapo_backends"
