language: generic
dist: trusty

services:
  - docker

env:
  global:
    - LAST_COMMIT_DATE=$(TZ=UTC git show --quiet --date='format-local:%Y%m%d_%H%M%S' --format="%cd")
    - BRANCH=$([ ${TRAVIS_BRANCH} == master ] && echo ${LAST_COMMIT_DATE} || echo ${TRAVIS_BRANCH})
    - DOCKER_REGISTRY="${ARTIFACTORY_DOCKER_REGISTRY}"
    - DOCKER=container_cache

# This build should not be triggered by tags
if: tags IS blank

before_install:
  - configure_jfrog_client
  - helm init --client-only

# Anything in install that returns a nonzero exit code will
# flunk the build and immediately stop. It's sorta like having
# set -e enabled in bash.
install:
  # run the initial setup
  #- make build-dev

# script always run to completion (set +e). All of these code checks are must haves
# in a modern Go project.
script:
  # Generate coverage and checkstyle report
  - make run-test
    #- make pact-test
    #- make docker-build

after_failure:
  - reports-publisher

after_success:
  - reports-publisher
    #- make deploy-k8s

deploy:
  - provider: script
    script: make docker-publish
    on:
      all_branches: true
      #- provider: script
      # script: make deploy-rancher
      #on:
      #tags: true
