language: generic
dist: trusty

services:
  - docker

env:
  global:
    - LAST_COMMIT_DATE=$(TZ=UTC git show --quiet --date='format-local:%Y%m%d_%H%M%S' --format="%cd")
    - BRANCH=$([ ${TRAVIS_BRANCH} == master ] && echo ${LAST_COMMIT_DATE} || echo ${TRAVIS_BRANCH})
    - DOCKER_REGISTRY="${ARTIFACTORY_DOCKER_REGISTRY}"

# This build should not be triggered by tags
if: tags IS blank

before_install:
  - configure_jfrog_client
  - helm init --client-only

install: skip

script:
  - make test
    #- make pact-test

after_failure:
  - reports-publisher

after_success:
  - reports-publisher

deploy:
  - provider: script
    script: make docker-publish
    on:
      all_branches: true
  - provider: script
    script: make helm-publish
    on:
      tags: true
