apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: {{ .Values.prometheus.port | quote }}
    prometheus.io/scrape: {{ .Values.prometheus.enabled | quote }}
  name: {{ include "goms.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "goms.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.prometheus.enabled }}
    - port: {{ .Values.prometheus.port }}
      targetPort: prom
      protocol: TCP
      name: prom
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "goms.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
