FROM golang:1.11 AS go

ARG APPNAME

ADD ./ /goms
WORKDIR /goms
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o /app.linux cmd/$APPNAME/main.go

FROM alpine:3.8

COPY --from=go /app.linux /

EXPOSE 8080
CMD ["/app.linux"]
