FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*

ARG GIT_COMMIT
ARG GIT_BRANCH
ARG BUILD_CREATOR
ARG APPNAME
ARG BINARY

EXPOSE 8080
WORKDIR /home/user/app/

# Need to define ENV in order to use it in CMD
ENV BINARY $BINARY
CMD ./$BINARY

LABEL branch=$GIT_BRANCH \
   commit=$GIT_COMMIT \
   build-creator=$BUILD_CREATOR \
   appname=$APPNAME

COPY ${BINARY} /home/user/app/
RUN touch /home/user/app/$GIT_COMMIT
