FROM golang:1.11

ENV TZ America/Santiago

# Copy zoneinfo file and then remove cache
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime

EXPOSE 8080

ARG APPNAME
ARG MAIN_FILE
ENV APPNAME ${APPNAME:-goms}
ENV MAIN_FILE ${MAIN_FILE:-main.go}

WORKDIR /go/src/github.mpi-internal.com/Yapo/${APPNAME}
COPY . .
RUN make setup

RUN ["go", "get", "github.com/githubnemo/CompileDaemon"]
ENTRYPOINT CompileDaemon -log-prefix=false -build="go build -v -o ${APPNAME} ./${MAIN_FILE}" -command="./${APPNAME}"
