FROM golang:1.13

ENV TZ America/Santiago

# Copy zoneinfo file and then remove cache
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime
RUN GO111MODULE=off go get -u github.com/golangci/golangci-lint/cmd/golangci-lint \
    github.com/jstemmer/go-junit-report \
    github.com/axw/gocov/gocov \
    github.com/AlekSi/gocov-xml \
    github.com/golangci/golangci-lint/cmd/golangci-lint \
	github.com/githubnemo/CompileDaemon

EXPOSE 8080

ARG APPNAME
ARG MAIN_FILE
ENV APPNAME ${APPNAME:-goms}
ENV MAIN_FILE ${MAIN_FILE:-main.go}

WORKDIR /app

ENTRYPOINT CompileDaemon -log-prefix=false -build="go build -v -o ${APPNAME} ./${MAIN_FILE}" -command="./${APPNAME}"
