FROM golang:1.10 AS go

ARG APPFOLDER
ARG APPNAME

ADD ./ /go/src/github.schibsted.io/Yapo/${APPFOLDER}
RUN make -C /go/src/github.schibsted.io/Yapo/${APPFOLDER} setup
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o /app.linux /go/src/github.schibsted.io/Yapo/${APPFOLDER}/cmd/${APPNAME}/main.go

FROM alpine:3.8
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*

ARG GIT_COMMIT
ARG GIT_BRANCH
ARG GIT_COMMIT_DATE
ARG BUILD_CREATOR
ARG APPNAME

ENV PS1="\[\e[1;32m\]$APPNAME \[\e[1;31m\][`pwd`] # \[\e[0m\]"

# Need to define ENV in order to use it in CMD

LABEL branch=$GIT_BRANCH \
   commit=$GIT_COMMIT \
   commit-date=$GIT_COMMIT_DATE \
   build-creator=$BUILD_CREATOR \
   appname=$APPNAME

COPY --from=go /app.linux /home/user/app/
RUN touch /home/user/app/$GIT_COMMIT

# Package tzdata is needed before setting TZ ENV variable
RUN apk update && apk add ca-certificates && apk add -U tzdata
ENV TZ America/Santiago
# Copy zoneinfo file and then remove cache
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && rm -rf /var/cache/apk/*

EXPOSE 8080
WORKDIR /home/user/app/

CMD ["./app.linux"]
