FROM alpine:3.11
# Package tzdata is needed before setting TZ ENV variable
RUN apk update && apk add ca-certificates && apk add -U tzdata
ARG GIT_COMMIT
ARG APPNAME
ENV PS1="\[\e[1;32m\]$APPNAME \[\e[1;31m\][`pwd`] # \[\e[0m\]"
ENV TZ America/Santiago
# Copy zoneinfo file and then remove cache
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && rm -rf /var/cache/apk/*
WORKDIR /home/user/app/
EXPOSE 8080
COPY app /home/user/app/
RUN touch /home/user/app/$GIT_COMMIT
CMD ["./app"]